### ISSUE TITLE
Non ASCII characters in comments cause issues on python 2.7.12

### ISSUE THREAD

**Issue by abattye** [F5Networks/f5-openstack-agent#1029]
The agent (and maybe also driver) fails to run due to the presence of the non ascii ® character in comments. 

The error generated is (for example) :

SyntaxError: Non-ASCII character '\xc2' in file /var/lib/openstack/src/f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py on line 238, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Please either remove these characters or specify an encoding as per pep-0263

**Comment by richbrowne** [comment]
These characters were pulled as part of a previous commit.  I could find no instances of non-ASCII characters remaining.

**Comment by mattgreene** [comment]
Recommend adding a pipeline check in travis (script or pep enforcement) to block future changes from introducing these characters.

**Comment by mattgreene** [comment]
Filed https://github.com/F5Networks/f5-openstack-agent/issues/1057 as enhancement to prevent future problems.
