### ISSUE TITLE
Removal of L7 policy fails to remove all ESD-related objects.

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#1043]
#### Agent Version
All supported with ESD

#### Operating System
N/A

#### OpenStack Release
All supported

#### Description
You can see ESDs fail by simply creating an ESD with profiles, iRules, and traffic policies. The ESD gets added when you add the Neutron L7 policy, but when you remove the L7 policy, not all the object associated with the ESD get removed from the virtual server. Adding and removing L7 policies should add or remove all tagged attributes of the ESD associated with the policy name.

#### Deployment
N/A

**Comment by pjbreaux** [comment]
@mattgreene: is this bug referring to multiple ESD policies? I think I need more context around the failure, as I cannot recreate.

**Comment by mattgreene** [comment]
@pjbreaux Try creating an ESD that sets every option possible. On delete, you should see that not all objects created for the ESD are removed. I believe this is for a single ESD.

**Comment by pjbreaux** [comment]
@mattgreene: that is what I am testing with. The demo.json file we install by default does set every option we support.

**Comment by pjbreaux** [comment]
@mattgreene: stopped the test after removing the policy, but I see all objects have been removed. There must be something else going on here. @jgruber: please update this issue with the esd you used and the exact behavior you see.

**Comment by richbrowne** [comment]
Fixed by: ffe2b124bb51f10b0eb10d774720d9985507b66b
