### ISSUE TITLE
The github repo web interface still has a reference to readthedocs.io in repo title description

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#1048]
#### Agent Version
Any

#### Operating System
github.com web interface

#### OpenStack Release
Any

#### Description
The github.com web interface has a link to readthedocs.io in the repo description

#### Deployment
Goto https://github.com/F5Networks/f5-openstack-agent and read the repo discription

**Comment by jputrino** [comment]
Fixed.
