### ISSUE TITLE
README.rst has bad markup pointing to |version|

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#1050]
#### Agent Version
Any

#### Operating System
Any

#### OpenStack Release
master branch

#### Description
When you goto https://github.com/F5Networks/f5-openstack-agent and look at the version link of the README.rst you get: "version |release|" not the rendered release number.

#### Deployment
Goto: https://github.com/F5Networks/f5-openstack-agent and look at the version link in a browser.

**Comment by jputrino** [comment]
@jgruber This is functioning as intended. Sphinx substitutions do not render in GitHub.
