### ISSUE TITLE
Source code renaming in dependencies cause objects to be unavailable across versions

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-agent#1054]
Prior to `ocata` an exception named `NeutronException` was defined in:
`neutron.commmon.exceptions` by today `ocata` has migrated `NeutronException` into `neutron_lib.exceptions`.

Our code has:   `from neutron.common import exceptions as q_exception` followed by:
`q_exception.NeutronException`.   The `NameError` associated with this pattern is not detected until late in the process.

We can make our code more sensitive to external dependency renaming by changing our import statements to explicitly name the most derived name.
e.g.
`from neutron_lib.exceptions import NeutronException as NL_NeutronException`

**Comment by richbrowne** [comment]
Will fix as part of the uplift to Ocata
