### ISSUE TITLE
agent_manager.LbaasAgentManager.has_provisioning_status_of_error

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-agent#1056]
1.  Service objects are JSON blobs, so we know the possible data types in a `json.loads`-ed dictionary.
2.  "provisioning_status" is a string literal key in a dict
3.  `has_provisioning_status_of_error` should have no side effects and should return a boolean.

**Comment by richbrowne** [comment]
Please move this issue to your private fork.  If this is part of ongoing work.
