### ISSUE TITLE
Attempted Application of Invalid ESDs Yields Silent (Unintended?!) Configuration

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-agent#1065]
This issue is referenced in the "Slack":  F5OpenstackDev Team Channel: #esd
The current behaviour of the ESD feature is that invalid ESDs are silently discarded.   It is unlikely that the User will provide an invalid ESD intentionally.   It is likely that the User misexpressed an intended configuration.   Rather than silently discarding that intention, it may be more intuitive for the agent to exit upon detection of the invalid state with an informative message.   This will provide timely (immediate) feedback to the User letting them know that the intended state was not entered.

I believe we can achieve this more intuitive interface by adding a `raise` statement *within* the except block on this line:

https://github.com/F5Networks/f5-openstack-agent/blob/master/f5_openstack_agent/lbaasv2/drivers/bigip/esd_filehandler.py#L163

**Comment by richbrowne** [comment]
If a user provides an ESD which cannot be applied the listener that applies is is marked in 'ERROR' state.  This is an indication that the applied policy did not succeed.

We can write a neutronless test, that applies a policy that does not exist and verify that there is an ESD application error by checking the provisioning status of the listener.
