### ISSUE TITLE
Disconnected Service Deployment

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#109]
# Introduction
This document is meant to provide a lightweight, high-level view of the “Disconnected Service Deployment” capability in the F5 OpenStack Agent, hereafter known as “agent”.  The business driver for this capability is a requirement to support “Hierarchical Port Binding”; as possible via the ML2 plugin driver architecture.

# Background
The agent assumes that a Neutron network will already exist when attempting to create Neutron LBaaS objects.  The service model constructed and sent to the agent, and subsequent RPC from the agent back to Neutron for discovery purposes will always have complete information.  Therefore, the agent is able to immediately create the necessary configuration on attached BIG-IP(s).

Deploying an OpenStack network architecture with hierarchical port-binding breaks current agent assumptions.  The key difference is that the network to which the BIG-IP should attach may not exist at the time Neutron LBaaS sends loadbalancer requests to the F5 plugin driver.   The network design provides an outward-facing segment ID to connect to the public/provider network.  This ‘top’ network can cascade through a series of one or more intermediate segments before reaching the ‘bottom’ network to which the BIG-IP will be attached.

# Proposal
The agent will be modified to create a “disconnected network” in order to support the “delayed activation” of loadbalancer objects.  This will become the default behavior and not modifiable by the operator.  For deployments using pre-existing Neutron networks, there may be a minor increase (on the order of seconds) in the time to activate BIG-IP configuration.  For deployments that create networks on-the-fly, the agent will poll for a maximum of 5 minutes waiting for the BIG-IP facing network to become available.  The agent does not attempt to create a Virtual Server until both a loadbalancer AND listener object have been created.  The listener object will sit in “PENDING_CREATE” state until either the network is created or the 5-minute timeout occurs.

### Disconnected Network
The agent will create a VLAN interface named “disconnected-vlan” within each tenant partition that is not connected to an external interface.  Therefore, the interface will not be capable of sending or receiving data traffic.  But it provides sufficient configuration to support creation of loadbalancer objects.

### Delayed Activation
Specific network fields in the Service Model will be allowed to point to, or contain, a non-existent value.  The agent will retain its current behavior that immediately translates loadbalancer objects to the appropriate BIG-IP configuration.  But the Virtual Server/Listener will be connected to the tenant’s disconnected network.  For this proposal, the segment ID (i.e. VXLAN tunnel ID) can be empty even though the Service Model should still contain the name of the network missing an ID.

## Deliverables

* Enhanced F5 OpenStack agent

### Assumption
1. Operator creates loadbalancer with the parent subnet_id
2. ML2 plugin driver creates the network hierarchy
3. Agent must detect a hierarchical network and traverse down to locate the child network
4. Agent polls for child subnet_id
5. Agent requests a neutron port (for the listener, a.k.a. VIP) on the child subnet_id
6. Agent creates the tenant interface on BIG-IP and binds the listener (Virtual Server address) 

### Sequence Diagram
![image](https://cloud.githubusercontent.com/assets/14237463/15228486/a5563d28-1849-11e6-89b5-37f8edf02ae7.png)

**Comment by jputrino** [comment]
Somewhat nitpicky issue: In the ini file, line 234, can we change 'name' to 'type'? 'Name' suggests that the user should provide the name of the physical network, not the `physical_network` attribute.
