### ISSUE TITLE
Agent fails to delete L2 population FDB record

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#1145]
#### Agent Version
8.3.7.b2

#### Operating System
CentOS

#### OpenStack Release
Liberty

#### Description
Agent does not remove an FDB entry when receiving FDB updates from neutron L2 population events. To protect against removing static ARP entries, the agent removes the IP address from the FDB update record, which in turn causes the agent to skip over deleting the FDB record.

#### Deployment
Stand alone BIG-IP with L2 population enabled.

**Comment by richbrowne** [comment]
Please port into all affected versions
