### ISSUE TITLE
Neutron orphaned member didn't get recreated

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-agent#1186]
* Details: 
The test case scenario is to delete a member on the bigip that is create through Neutron. Then wait for the service_resync_interval to timeout and the deleted member should get recreated. 

#### OpenStack Release
Newton

#### Deployment
I ran this test against one bigip in the bigip cluster in Newton stack.

**Comment by richbrowne** [comment]
The issue is with test timing.
