### ISSUE TITLE
Inconsistency in cleaning Orphaned Objects - Virtual Servers

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-agent#1195]
* Details:
Orphaned virtual server on the bigip doesn't get cleaned. This test is part of the test_orphaned_objects_singlebigip testsuite. I tested it against mitaka and Newton stacks and the failure seems consistent between the two. 

#### OpenStack Release
Mitaka, Newton

#### Deployment
The configuration change that is required for this test is to set the "service_resync_interval" field to 60 seconds in the f5_openstack_agent.ini file.

**Comment by szakeri** [comment]
@richbrowne this test has passed before but as of today I see consistent failure in both mitaka and Newton. Also I increased the wait time in the test to 300s but still it was failing.

**Comment by richbrowne** [comment]
The issue was with the test timing.
