### ISSUE TITLE
LbaaS agent code modification to make it compatible with Ocata release.

### ISSUE THREAD

**Issue by kush1093** [F5Networks/f5-openstack-agent#1264]
* Title: LbaaS agent that runs in newton release doesn't start/work in Ocata. So few modifications are needed.

* Details: For enhancements, fill out the template below.

#### OpenStack Release
Ocata release

#### Description
The modules are described under different python libraries in Ocata. So necessary changes are to be made to the existing code.

* Details: For bugs, fill out the template below.

#### Agent Version
<Fill in the version you have installed, such as 2.0.1>

#### Operating System
<Fill in the host OS of the machine running the agent, such as Centos 7>

#### OpenStack Release
<Fill in the OpenStack release, such as Liberty>

#### Description
<Describe the bug in detail, steps taken prior to encountering the issue, yand a short explanation of you have deployed openstack and F5 agent>

#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

**Comment by sjsharma2001** [comment]
This effort is being tracked internally.
