### ISSUE TITLE
Installation instructions need to be updated 

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-agent#260]
#### OpenStack Release
Liberty

#### Description
The agent installation instructions need to be updated. See f5-openstack-lbaasv2-driver [issue 200](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/200) for details.

Install instructions are found in this file: https://github.com/F5Networks/f5-openstack-agent/blob/liberty/docs/topic_install-f5-agent.rst

**Comment by mattgreene** [comment]
The driver bug (200) is closed, so closing this issue.
