### ISSUE TITLE
Loadbalancer comes up ACTIVE, OFFLINE after creation

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-agent#284]
* Title: 

Loadbalancer comes up OFFLINE after creation, the expected status is ONLINE.

#### OpenStack Release
Liberty

#### Description
I ran into this problem during running Tempest scenario tests. It tries to create a loadbalancer, listener and pool member. It never get passed loadbalancer creation, since it expects ONLINE status for loadbalancer.

#### Agent Version
Liberty head with the disconnected feature present.

**Comment by mattgreene** [comment]
This PR has been merged through liberty->mitaka->master.
