### ISSUE TITLE
openstack-agent download fails 

### ISSUE THREAD

**Issue by fieldedge** [F5Networks/f5-openstack-agent#289]
* Title: A short but descriptive summary of the issue, whether it be a bug or enhancement.
* Attachments: For bugs, attach the agent log and configuration files
  * /etc/neutron//services/f5/f5-openstack-agent.ini
  * /var/log/neutron/f5-openstack-agent.log
* Details: For enhancements, fill out the template below.

#### OpenStack Release
Liberty

#### Description
I am trying to upgrade LBaaS plugin from v8.0.5 to v8.0.7, then attempt to download f5-openstack-agent, but it seems to fail. 

Looking at the following site, and try to get the rpm file.  The file seems to not be there.
http://f5-openstack-agent.readthedocs.io/en/liberty/index.html#home

The following is command log which is described in RPM package. 

[root@openstack ~]# curl -L -O https://github.com/F5Networks/f5-common-python/releases/download/v8.0.8/f5-openstack-agent-8.0.8-1.el7.noarch.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     20      0 --:--:--  0:00:01 --:--:--    20
[root@openstack ~]# file f5-openstack-agent-8.0.8-1.el7.noarch.rpm
f5-openstack-agent-8.0.8-1.el7.noarch.rpm: ASCII text, with no line terminators
[root@openstack ~]# cat f5-openstack-agent-8.0.8-1.el7.noarch.rpm
{"error":"Not Found"}
[root@openstack ~]#

#### Agent Version
v8.0.7

#### Operating System
Centos 7

#### OpenStack Release
Liberty

#### Deployment
One OpenStack controllers with one standalone F5 agent managing a single BIG-IP appliance

**Comment by richbrowne** [comment]
Hi,

  Thank you for bringing this to my attention.  Please use this URL:

 https://github.com/F5Networks/f5-openstack-agent/
releases/download/v8.0.7/f5-openstack-agent-8.0.7-1.el7.noarch.rpm
<https://github.com/F5Networks/f5-common-python/releases/download/v8.0.8/f5-openstack-agent-8.0.8-1.el7.noarch.rpm>

We are in the process of releasing 8.0.8 and the docs are in the process of
update.

Cheers,

Rich
