### ISSUE TITLE
python-f5-openstack-agent init.d script of deb package points to wrong path

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#304]
#### OpenStack Release
Mitaka
#### Description

Using python-f5-openstack-agent_9.0.2-1_1404_all.deb

The script /etc/init.d/f5-oslbaasv2-agent has the following variable:

DAEMON="/usr/local/bin/${NAME}"

and it should be

DAEMON="/usr/bin/${NAME}"

#### Agent Version
ii  python-f5-openstack-agent            9.0.2-1                                all          F5 Networks Agent for OpenStack services

#### Operating System
Mirantis 9.0

**Comment by richbrowne** [comment]
Could you please try the attached file to see if this is better?  I don't have a debian setup other than devstack.


[f5-oslbaasv2-agent.gz](https://github.com/F5Networks/f5-openstack-agent/files/457098/f5-oslbaasv2-agent.gz)

**Comment by richbrowne** [comment]
This link is probably more convenient.

https://github.com/richbrowne/f5-openstack-agent/blob/issue-304/etc/init.d/f5-oslbaasv2-agent

**Comment by alonsocamaro** [comment]
Hi again

I had further feedback wrt this.

As I mentioned before the new version of the init.d script starts/stops correctly the agent but I find that after the agent is stopped the agent is still listed in "neutron agent-list" and it is listed as not alive. Is this expected? 

If I start again the agent, it gets the status alive again.

If this behavior is expected, how can I clear an stale agent from the neutron's agent list? ie, in the following example you can see the first LBaaSv2 agent which is stale and a second one which is running just fine.

```
root@node-2:/etc/init.d# neutron agent-list 
+--------------------------------------+----------------------+--------------------------------------------------------+-------------------+-------+----------------+---------------------------+
| id                                   | agent_type           | host                                                   | availability_zone | alive | admin_state_up | binary                    |
+--------------------------------------+----------------------+--------------------------------------------------------+-------------------+-------+----------------+---------------------------+
| 0b4fd05f-76ca-482f-acef-2a0415a4a901 | Loadbalancerv2 agent | node-2.domain.tld:28d5268a-6b32-59f2-81bd-f33726010839 |                   | xxx   | True           | f5-oslbaasv2-agent        |
| 12ad3c94-6f2a-44e2-9e43-2a625640b396 | Metadata agent       | node-2.domain.tld                                      |                   | :-)   | True           | neutron-metadata-agent    |
| a60a54a0-7648-4b85-8e2c-d0f1feacb304 | Open vSwitch agent   | node-2.domain.tld                                      |                   | :-)   | True           | neutron-openvswitch-agent |
| a6b34875-f5e6-498c-ad6f-ccec467f5a9e | Open vSwitch agent   | node-1.domain.tld                                      |                   | :-)   | True           | neutron-openvswitch-agent |
| c49a7ac4-2815-4c07-9f5f-87ac7b55d39d | DHCP agent           | node-2.domain.tld                                      | nova              | :-)   | True           | neutron-dhcp-agent        |
| dcd6ac77-547f-4b8a-a5c9-2b2a4537504e | Loadbalancerv2 agent | node-2.domain.tld:707729b3-3e0c-53fe-88b4-f74911b02101 |                   | :-)   | True           | f5-oslbaasv2-agent        |
| f00f52ee-4031-4402-8b6e-0c3025d5e22a | L3 agent             | node-2.domain.tld                                      | nova              | :-)   | True           | neutron-l3-agent          |
+--------------------------------------+----------------------+--------------------------------------------------------+-------------------+-------+----------------+---------------------------+

```

Many thanks
