### ISSUE TITLE
Remove unused score functions in the stats_helper.py file

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-openstack-agent#318]
#### OpenStack Release

Liberty+
#### Description

There are a number of methods in the `stats_helper` module that are not used by the OpenStack code.  They were left over from a previous version of the library that was used in a different project. This is now dead code and should be removed.

**Comment by dflanigan** [comment]
See this fix in master in commit: https://github.com/F5Networks/f5-openstack-agent/commit/667dfc91f640495a389c2b9accc01cc2d4c73bfe
