### ISSUE TITLE
Does not syntax check object names for spaces that BIG-IP doesn't accept

### ISSUE THREAD

**Issue by jat190** [F5Networks/f5-openstack-agent#326]
Title: Openstack allows object names with spaces in them, BIG-IP does not.
try and create a pool with the name "Pool 1" which, unfortunately is the default name, you get an error in the log file

The requested object name (/Project_5ca8171d93b743f9a776d54f440d8f40/Pool 3) is invalid.","errorStack":[],"apiError":3}'
9.0.3 agent
mitaka
F5 11.5.4 and 12.1HF1

Need to add validation for spaces in object names

**Comment by jgruber** [comment]
caused by same issue as #281

**Comment by dflanigan** [comment]
Bug 281 is closed.
