### ISSUE TITLE
Creating a listener with the same name as a previous listener overwrites the previous virtual server.

### ISSUE THREAD

**Issue by jat190** [F5Networks/f5-openstack-agent#329]
Title: 
If you create lb1 with listener list1 and pool1 , then you create lb2 with listener list1 and pool 1 , Openstack has that as two separate objects, but the agent ends up overwriting the initial virtual server with the data from the new vip.
Openstack has 2 load balancers with different IP's.  F5 has 1 virtual server with the new IP only.

agent 9.0.3
Mitaka

**Comment by jgruber** [comment]
duplicate of #281
