### ISSUE TITLE
Remove reference to vcmp oslo conf in disconnected service tests.

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#340]
* Title: A reference to a vcmp json file in disconected service tests needs to be yanked
* Details: This reference will cause failures when any test runs for disconnected service, because the json file does not exist in that directory. The reference is here: https://github.com/F5Networks/f5-openstack-agent/blob/master/test/functional/neutronless/l2adjacent/test_disconnected_service_creation.py#L35

**Comment by mattgreene** [comment]
@pjbreaux: Does this bug still exist?  I thought I saw a commit go in for this issue.

**Comment by pjbreaux** [comment]
Tis fixed.
