### ISSUE TITLE
9.0.2 release notes clarification on agent's high availability

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#341]
#### OpenStack Release

Mitaka
#### Description

In http://f5-openstack-lbaasv2-driver.readthedocs.io/en/mitaka/release_notes.html (this link currently mentiones they apply to v9.0.2)

It is stated that "Agent redundancy and capacity-based scale out" is supported yet "Agent High Availability (HA)" is not.

Could you please clarify If "Agent redundancy" is different to "Agent High Availability"?

Thanks 

```
  Ulises
```
#### Agent Version

9.0.2
#### Operating System

MOS 9.0

**Comment by alonsocamaro** [comment]
Also the following link doesn't contain the same content features/caveats yet I understand it should

http://f5-openstack-lbaasv2-driver.readthedocs.io/en/v9.0.2/release_notes.html

Additionally http://f5-openstack-lbaasv2-driver.readthedocs.io/en/latest/release_notes.html currently points to shows v9.0.2 yet v9.0.3 is already available.

I hope this helps

Many thanks

         Ulises

**Comment by richbrowne** [comment]
Moved on to 9.4.
