### ISSUE TITLE
missing add_f5agent_environment utility

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#342]
#### OpenStack Release
Mitaka

#### Description

Hi

I wanted to explore the "Differentiated Service Environments" feature and I found that the 9.0.3 packages of the agent (both rpm and .deb) or the github repository don't have the add_f5agent_environment utility pointed in the documentation

#### Agent Version
9.0.3
#### Operating System
Mirantis 9.0

**Comment by mattgreene** [comment]
The release notes for 9.0.3 state that "Differentiated Service Environments" is not yet supported.  9.0.3 was a bug-fix release.  Can you provide a link to the documentation that points to the missing utility?

**Comment by richbrowne** [comment]
I know that this is included in the most recently packaged debs.  We are
still working through the testing to get this release available.

**Comment by alonsocamaro** [comment]
@mattgreene I don't find it now. Maybe I got confused? Feel free to close the case.

Many thanks

**Comment by richbrowne** [comment]
Ulises there is a new release available now.  It's version 9.1.
