### ISSUE TITLE
Test vcmp has hardcoded 12.0 version values in the tests and test files

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#381]
- Title: 
- Details: The VCMP neutronless tests are inflexible to testing multiple versions of TMOS. We need to have the test runner provide a release (tmos version) when the test is run, so the test can know what to expect for tmos version. This exists in two places: one is in the vcmp_uris.json file and the other is in the test, where the vcmp guests has names like bigip-12.0. Those need to be more generic.

**Comment by dflanigan** [comment]
The merge comment did not reference this issue correctly and could not close this issue automatically. (And I observed the commits in master.)
