### ISSUE TITLE
RPM depedencies for f5-openstack-agent 9.1.0

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-openstack-agent#384]
#### Agent Version
9.1.0

#### Operating System
Centos 7

#### OpenStack Release
Mitaka

#### Description
Following the RPM install directions the RPM do not have the correct dependencies for the f5-sdk RPM (references 1.0.9 instead of 1.1.0).

% rpm -qpR  f5-sdk-1.5.0-1.el7.noarch.rpm
f5-icontrol-rest = 1.0.9

**Comment by richbrowne** [comment]
Fixed documentation.
