### ISSUE TITLE
http_method for monitor is always set to GET

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#391]
http_method for monitors is not set by the F5 agent. For monitors created by F5, the http-method option is always set to GET (default).

**Comment by dflanigan** [comment]
http_method HTTP verb for health monitors is not sent to F5. F5 monitor is always set to HTTP verb GET (default).  Example of other verbs that could be supported are HEAD.

Jeff- What are the verbs that we need to support?

**Comment by jlongstaf** [comment]
The verbs are the set of valid HTTP methods: 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'TRACE', 'OPTIONS', 'CONNECT', 'PATCH'

**Comment by richbrowne** [comment]
Duplicate, track work in #1069
