### ISSUE TITLE
Virtual servers and pools are not created when name begins with number.

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#394]
Virtual servers and Pools didn’t get created in F5 when corresponding OS object name starts with number. No message is send to clients. If one object with a “wrong” name is created nothing can be changed anymore for that virtual server and client didn’t get any messages about that. Cli also allows the creation of these objects which are not created in F5. (also noted is if a space is in the name the same is seen)

**Comment by dflanigan** [comment]
caused by same issue as #281

**Comment by dflanigan** [comment]
Bug 281 is closed.
