### ISSUE TITLE
rpm packages's init.d script is not compatible with Suse Cloud 6

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#418]
Hi 

It appears that Suse lacks the the log_daemon_msg and start-stop-daemon commands hence the /etc/init.d/f5-oslbaasv2-agent doesn't work:

Nov 17 08:36:33 dc8-1f-66-b8-bd-ca f5-oslbaasv2-agent[42674]: /etc/init.d/f5-oslbaasv2-agent: line 124: log_daemon_msg: command not found
Nov 17 08:36:33 dc8-1f-66-b8-bd-ca f5-oslbaasv2-agent[42674]: /etc/init.d/f5-oslbaasv2-agent: line 71: start-stop-daemon: command not found
Nov 17 08:36:33 dc8-1f-66-b8-bd-ca f5-oslbaasv2-agent[42674]: /etc/init.d/f5-oslbaasv2-agent: line 136: log_end_msg: command not found

**Comment by alonsocamaro** [comment]
I've created a replacement script which might help you

https://github.com/alonsocamaro/public/blob/master/openstack_suse_cloud_v6/f5-oslbaasv2-agent

**Comment by mattgreene** [comment]
Suggestion from @alonsocamaro:

Something that I haven’t researched fully but I think we should in the mid term is to stick to  (Linux Standards Base) functions. 

http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptfunc.html

In the Linux distro doesn’t include these by default they typically provide a lsb compatibility package that implements it. We would just have that compatibility package as requirement. Our agent's initialization is not complex so I’m positive that LSB provided functions will be enough

Then we would have a single init.d script for all distros.

**Comment by mattgreene** [comment]
Here's our plan after an engineering discussion:
* Re-write the existing init script to comply with LSB functions to make a single script that will work for both Ubuntu and OpenSuSE.
* Continue using the existing systemctl script for CentOS/Red Hat as the default for internal dev and test environments.  This is the expected paradigm on CentOS/Red Hat.
* Create a new point test for the new generic init script on CentOS

**Comment by ssorenso** [comment]
Hi @alonsocamaro,

I'm taking a look at this.  Rich has explained quite a bit to me about what's going on with what we're doing and not doing here, and I've done some research on my own.  I am going to...

- Follow Matt's plan on this by altering the script that we have to reach his first bullet point's need
  - This will hopefully [solve this issue as well](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/204), at least at face value.
  - Also be putting a note in that case with additional, proposed elements on how to approach that problem
- Will use `logger` as well as `echo` and depend on the fact that the user has set up their own logging as per the multiple references to:
> message to an unspecified log file
Within the LSB documentation.

I also have a proposal to solve the issue of the unhandled, import exception in this case's sister case.

Will this satisfy your need?

**Comment by alonsocamaro** [comment]
Hi 

Could you indicate in which packages this has been fixed?

Many thanks

      Ulises
