### ISSUE TITLE
Virtual Server is bound only to disconnected_network

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#423]
#### Agent Version
Unknown

#### Operating System
N/A

#### OpenStack Release
Liberty

#### Description
Deploy F5 agent in 'global routed mode'.

#### Deployment
Trying to use GRM and the VLAN/Tunnel is always defaulting to "disconnected_network".  Using the stock GRM ini from http://f5-openstack-lbaasv2-driver.readthedocs.io/en/liberty/_downloads/f5-openstack-agent.grm.ini

#### Workaround
Comment out the disconnected_service section in the create_listener code it works as expected.

**Comment by dflanigan** [comment]
@richbrowne Is fix for #423 in PR #524 ?

**Comment by richbrowne** [comment]
We dont use disconnected networks anymore.  HPB was refactored.
