### ISSUE TITLE
Agent manager not updated to call service_rename_required

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#427]
The agent manager is calling the old update interface and needs to be updated to call service_rename_required and not rename_required

#### OpenStack Release
Liberty

#### Description
Change the validate_service method to call correct function.

**Comment by dflanigan** [comment]
This bug will resolve when fix merges into master.

**Comment by mattgreene** [comment]
Change merged to master but issue did not automatically close as expected.
