### ISSUE TITLE
Race condition in disconnected network scenario

### ISSUE THREAD

**Issue by abattye** [F5Networks/f5-openstack-agent#443]
We are seeing a race condition using the disconnected feature with Neutron hierarchical port binding.  It happens the first time a LB/Listener is created on a network and all subsequent processing of the entities on the device fail. This Gist shows the stacktrace associated with the failure https://gist.github.com/abattye/b097578432d0ca529b9b0aa9dfbc052e 

The problem is 100% reproducible in our environment. 

After the failure, the VLAN object is available and subsequent create attempts work. 

We are running v9.1.0 of the driver/agent against stable/mitaka neutron/neutron-lbaas.

The attached stacktrace was created with vCMP active, but we see the same issue without.

**Comment by dflanigan** [comment]
Waiting for more information from @abattye

**Comment by mattgreene** [comment]
Believe this issue is resolved via https://github.com/F5Networks/f5-openstack-agent/issues/506, which reimplements HBP to support the generic Cisco ML2 mechanism driver which retaining backwards compatibility with the legacy implementation.
