### ISSUE TITLE
Deleting last VLAN in VCMP scenario results in all VLANs being removed from guest

### ISSUE THREAD

**Issue by abattye** [F5Networks/f5-openstack-agent#447]
In a vCMP enabled scenario we are seeing an issue that when the last load balancer in the system is deleted then all VLANs assigned to the VCMP guest are removed, including those not managed but the Openstack agent. 

This leads to a situation where the management VLAN is removed and the guests are left in a disconnected state.

**Comment by pjbreaux** [comment]
@abattye: Is that management VLAN in the Common partition, or in your tenant's?

**Comment by abattye** [comment]
hi, the management VLAN was created manually in the host and asscoiated to the guest as part of the guest setup. The VLANs are in the common partition of the guest and host. When we create LBs via Openstack a 'tenant' VLAN is created for each network segment,  when the last one is deleted the tenant VLAN is deleted from the host as excpected. However the management VLAN is also disassociated from the guest (its kept in the common partition on the host). Obviously as I said above this leads the guests in a disconnected state and we have to manually associate the management VLAN to the guest to fix.

If you need more information or a short webex to reproduce please let me know, Matt has my contact details.

**Comment by pjbreaux** [comment]
Thanks, I'll try to recreate and get back to you if I need further assistance.

**Comment by pjbreaux** [comment]
@abattye: Which branch/release are you using of the agent and driver?

**Comment by abattye** [comment]
v9.1.0, we are also now testing on the mitaka brnach

**Comment by mattgreene** [comment]
@pjbreaux: Note that the version reflect the code will say v9.1.0, but @abattye was instructed to install from mitaka HEAD in order to obtain the recently collapsed L7 feature.

**Comment by pjbreaux** [comment]
Got it. I'm looking at it now. Rich gave me a hint last night, so I'll get back in 30 minutes.

**Comment by pjbreaux** [comment]
Andrew, I have isolated this issue. It is a bug in the teardown of the guest's VLAN. I will update later today with the fix, after I've done some testing.

**Comment by pjbreaux** [comment]
@abattye: The commit will go in tomorrow morning. I think I'll make it to the liberty branch and merge it up to mitaka, since the issue exists in both branches. Thanks.

**Comment by pjbreaux** [comment]
@abattye: This fix has been merged into liberty, and we will merge the changes from liberty into mitaka today and run tests. Once we are satisfied, we will close this issue. Thanks for your assistance.

**Comment by abattye** [comment]
Thanks for the quick fix, I'll test it on Monday, hopefully the other issue thats with Jeff will also be included by then - if you have any info on that would be good to know.

**Comment by richbrowne** [comment]
Yes, we have merged this into Liberty also and are working on automating a
test for this in tempest.

**Comment by pjbreaux** [comment]
Closed by PR #472
