### ISSUE TITLE
TMOS 12.1 returns 404 when adding l7 policy to virtual

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#457]
#### OpenStack Release
mitaka

#### Description
When testing feature.l7switching branch, we discovered that 12.1 BIG-IP version returns an invalid 404 error when adding wrapper policy to a virtual server. The policy is actually attached, so everything works correctly. Other versions of BIG-IP (e.g., 11.6) work correctly.

**Comment by pjbreaux** [comment]
Fixed by PR #458
