### ISSUE TITLE
Remove unused and stale devtools directory

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-openstack-agent#461]
The [devtools](devtools) directory was created prior to standardizing our test environment. We have now standardized on [tox](http://tox.readthedocs.io/en/latest/) as our test runner and we will no longer work to keep the docker files and execution methods recorded in devtools up to date.

#### OpenStack Release
Liberty

#### Description
The devtools directory contains environment management and docker files that are not directly related to the success and testing of the project. Docker can still be used as a a tool for running the tests, but we must decouple the infrastructure and environment used to execute the tests from the tests and repo itself.

The expectation going forward is that users will use tox to execute whether on a workstation, VM, container etc...

**Comment by zancas** [comment]
Since none of the nightly regression tests depend on this directory I'm going to remove it now.

Developers who use content from that directory will still have it on their dev branches...  and can cherry pick it from the past if they need to port something from it, into the current test flow.

**Comment by zancas** [comment]
This has been fixed.
