### ISSUE TITLE
Functional tests in f5-openstack-agent/f5_openstack_agent/tests/functional/ need to be ignored

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#477]
#### Description
There are functional tests in f5-openstack-agent/f5_openstack_agent/tests/functional/ directory in the agent on the *mitaka* branch. These require a BIG-IP to run. These should be ignored in the travis build of the agent repo.

**Comment by dflanigan** [comment]
Make sure these tests move to the right location so that they still get run.
