### ISSUE TITLE
Pool member creation fails with network_type opflex

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#506]
#### Agent Version
9.2.0.b1

#### Operating System
N/A

#### OpenStack Release
Mitaka

#### Description
The fix for https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/353 enabled the F5 driver/agent to detect and bind a virtual server to a dynamic VLAN segment, created by Cisco ACI.  Now pool member creation fails because the agent cannot find the VLAN segment for the pool network.

Need to allow member creation with missing seg ID or network segment.  Community code already knows how to do the right thing to create a VLAN network segment under the opflex parent.  Follow that for member creation.  The current agent code expects the VLAN to be present prior to member creation.  For type opflex, need to move this earlier in the workflow.

#### Deployment
Cisco ACI (Cisco ML2 Mechanism Driver) with VLAN encapsulation for BIG-IP network connectivity.

**Comment by mattgreene** [comment]
```
def _create_port_for_load_balancer(self, context, lb_db, ip_address):
        # resolve subnet and create port
        subnet = self._core_plugin.get_subnet(context, lb_db.vip_subnet_id)
        fixed_ip = {'subnet_id': subnet['id']}
        if ip_address and ip_address != attributes.ATTR_NOT_SPECIFIED:
            fixed_ip['ip_address'] = ip_address
 
        port_data = {
            'tenant_id': lb_db.tenant_id,
            'name': 'loadbalancer-' + lb_db.id,
            'network_id': subnet['network_id'],
            'mac_address': attributes.ATTR_NOT_SPECIFIED,
            'admin_state_up': False,
            'device_id': lb_db.id,
            'device_owner': n_constants.DEVICE_OWNER_LOADBALANCERV2,
            'fixed_ips': [fixed_ip]
        }
 
        port = self._core_plugin.create_port(context, {'port': port_data})
        lb_db.vip_port_id = port['id']
        for fixed_ip in port['fixed_ips']:
            if fixed_ip['subnet_id'] == lb_db.vip_subnet_id:
                lb_db.vip_address = fixed_ip['ip_address']
                break
 
        # explicitly sync session with db
        context.session.flush()
```

**Comment by richbrowne** [comment]
Matt,

  What is the origin of this code?

**Comment by mattgreene** [comment]
This is community code that creates the loadbalancer port, which triggers the "correct" behavior (VLAN network segment creation).

**Comment by richbrowne** [comment]
[LoadbalancerDisconnected.docx](https://github.com/F5Networks/f5-openstack-agent/files/774711/LoadbalancerDisconnected.docx)

[LoadbalancerDisconnected.pdf](https://github.com/F5Networks/f5-openstack-agent/files/774712/LoadbalancerDisconnected.pdf)
