### ISSUE TITLE
Agent fails to communicate with Plugin Driver

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#512]
#### Agent Version
8.2.0.b1

#### Operating System
RHEL 7

#### OpenStack Release
Liberty (OSPv8)

#### Description
Install from RPM according to F5 documentation.  Agent fails to show up in 'neutron agent-list'.  The agent log contains the following error message:

```
2017-01-06 03:36:41.322 24675 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.agent_manager [-] Unable to retrieve ready service: Timed out waiting for a reply to message ID ce44399e19e74979bf62c639e1c312a6
```

Forced a re-install of driver shim, driver and agent.  Restarted agent, neutron-server, rabbitmq-server.  Rebooted all controllers.  No error messages seen in /var/log/neutron/server.log.  Appears that the agent is unable to communicate with the driver over the message queue.

#### Deployment
Three OpenStack controllers in HA, three F5 OpenStack agents, single BIG-IP

**Comment by richbrowne** [comment]
I looked at your configuration.  Strictly speaking the prefix length should not matter.  I suspect that you have an environment prefix mismatch on both the agent and network controller.  I would recommend that you do the following:

1.  Comment the environment_prefix variable in your f5-openstack-agent.ini file and restart the agents.  You should see that they report in to the driver by doing neutron agent-list.  The agent is trying to connect to an RabbitMQ queue named after the environment prefix that you named in your config file; however, there is not a queue on your network controller that was created by the driver that knows about nxgenaz2   The driver created message queues that have Project appended to them, not nxgenaz2.  You can verify this by running this command:

rabbitmqctl list_queues | grep f5

You can run this on both the agent and controller.

2.  If you need to set up a new environment, that is not named after the default environment ‘Project’ follow these instructions.

http://f5-openstack-lbaasv2-driver.readthedocs.io/en/mitaka/includes/topic_differentiated-services.html

This will inform the driver that the agent will be listening on a queue named after the environment nxgenaz2.  Ask us if you need help setting this up.

Regards,


Rich

**Comment by richbrowne** [comment]
I just wanted to add that once you have created a new class named after nxgenaz2 on the controller, you will then uncomment the environment_prefix in your configuration file.

**Comment by mattgreene** [comment]
Guidance from @richbrowne on setting up a new environment resolved the communication problem.  Dropping the severity of this bug in case we want to use this issue to provide a descriptive release note.
