### ISSUE TITLE
Loopback address cannot be used as pool member address

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#519]
#### OpenStack Release
Found in mitaka. I suspect this exists in liberty as well.

#### Agent Version
Head of mitaka branch as of 1/06/2017. Release is 9.2.0.b1.

#### Operating System
CentOS

#### Description
When creating a pool member, the CLI allows you to assign the loopback address (127.0.0.1) as the --address field, but this sends the loadbalancer into an ERROR state.

`
lbaas-member-create --address 127.0.0.1 --protocol-port 80 --subnet my_subnet my_pool
`

#### Deployment
1 agent, 1 BIG-IP

**Comment by richbrowne** [comment]
Won't fix.  The lb is in error state and that is appropriate.
