### ISSUE TITLE
Virtual enabled on all vlans for loadbalancer on common net

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#523]
If a network is in the list of common_networks and a loadbalancer (virtual server) is created on that network then the virtual is enabled on all vlans.  This is not the desired behavior.  The listener should only be enabled on the vlan that corresponds to the common network id.

#### OpenStack Release
Liberty

#### Description
If a network is in the list of common_networks and a loadbalancer (virtual server) is created on that network then the virtual is enabled on all vlans.  This is not the desired behavior.  The listener should only be enabled on the vlan that corresponds to the common network id.

#### Deployment
N/a

**Comment by dflanigan** [comment]
@richbrowne Is fix for #523 in PR #524 ?

**Comment by richbrowne** [comment]
This is fixed.
