### ISSUE TITLE
disconnected network neutronless tests failing with bad assertions

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#534]
Test failures result from making assertions about the name of the self ip created for the loadbalancers.
This is due to faulty assumptions about what the hostname of the bigip will be in different environments.

Also, for a tlc deployed stack the selfip name of the vtep is 'selfip.client' and not 'selfip.external'.  We
need to add variables for:

the vtep selfip name
the icontrol_fqdn

**Comment by dflanigan** [comment]
@richbrowne is #534 still valid with the new HPB implementation ?

**Comment by richbrowne** [comment]
These are not working as reported in TRTL
