### ISSUE TITLE
Disconnected test fails for 11.6.1 deployment

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#551]
# Create a 11.6.1 BIG-IP in the test lab.

testenv  create -p bigip_img:bigip-osready-11.6.1.1.0.326 --name bigip-11.6 --config bigip

# Run disconnected test:
tox -e functest -- --symbols ./testenv_symbols/testenv_symbols.json  test/functional/neutronless/disconnected_service/test_disconnected_
service_creation.py

The following failures occur:

========================================================================================= short test summary info =========================================================================================
FAIL neutronless/disconnected_service/test_disconnected_service_creation.py::test_featureoff_withsegid_lb
FAIL neutronless/disconnected_service/test_disconnected_service_creation.py::test_withsegid_lb
FAIL neutronless/disconnected_service/test_disconnected_service_creation.py::test_featureoff_withsegid_listener
FAIL neutronless/disconnected_service/test_disconnected_service_creation.py::test_withsegid_listener
FAIL neutronless/disconnected_service/test_disconnected_service_creation.py::test_nosegid_to_segid
FAIL neutronless/disconnected_service/test_disconnected_service_creation.py::test_featureoff_nosegid_common_lb_net

Stack trace from failure:

 assert create_uris == SEG_INDEPENDENT_LB_URIS | SEG_DEPENDENT_LB_URIS
E       assert set(['https:/...11.6.1', ...]) == set(['https://...11.6.1', ...])
E         Extra items in the left set:
E         'https://localhost/mgmt/tm/net/self/~TEST_128a63ef33bc4cf891d684fad58e7f2d~local-host-172.16.2.6.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20?ver=11.6.1'
E         Extra items in the right set:
E         'https://localhost/mgmt/tm/net/self/~TEST_128a63ef33bc4cf891d684fad58e7f2d~local-host-10-190-21-229.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20?ver=11.6.1'
E         Full diff:
E         set([u'https://localhost/mgmt/tm/ltm/snat-translation/~TEST_128a63ef33bc4cf891d684fad58e7f2d~snat-traffic-group-local-only-ce69e293-56e7-43b8-b51c-01b91d66af20_0?ver=11.6.1',
E         u'https://localhost/mgmt/tm/ltm/snatpool/~TEST_128a63ef33bc4cf891d684fad58e7f2d~TEST_128a63ef33bc4cf891d684fad58e7f2d?ver=11.6.1',
E         u'https://localhost/mgmt/tm/ltm/virtual-address/~TEST_128a63ef33bc4cf891d684fad58e7f2d~TEST_50c5d54a-5a9e-4a80-9e74-8400a461a077?ver=11.6.1',
E         u'https://localhost/mgmt/tm/net/fdb/tunnel/~TEST_128a63ef33bc4cf891d684fad58e7f2d~disconnected_network?ver=11.5.0',
E         u'https://localhost/mgmt/tm/net/fdb/tunnel/~TEST_128a63ef33bc4cf891d684fad58e7f2d~tunnel-vxlan-46?ver=11.5.0',
E         u'https://localhost/mgmt/tm/net/route-domain/~TEST_128a63ef33bc4cf891d684fad58e7f2d~TEST_128a63ef33bc4cf891d684fad58e7f2d?ver=11.6.1',
E         -      u'https://localhost/mgmt/tm/net/self/~TEST_128a63ef33bc4cf891d684fad58e7f2d~local-host-172.16.2.6.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20?ver=11.6.1',
E         ?                                                                                              ^ - ^^ ^^
E         +      u'https://localhost/mgmt/tm/net/self/~TEST_128a63ef33bc4cf891d684fad58e7f2d~local-host-10-190-21-229.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20?ver=11.6.1',
E         ?                                                                                              ^^^^^^  ^ ^^
E         u'https://localhost/mgmt/tm/net/tunnels/tunnel/~TEST_128a63ef33bc4cf891d684fad58e7f2d~disconnected_network?ver=11.6.1',
E         u'https://localhost/mgmt/tm/net/tunnels/tunnel/~TEST_128a63ef33bc4cf891d684fad58e7f2d~tunnel-vxlan-46?ver=11.6.1',
E         u'https://localhost/mgmt/tm/sys/folder/~TEST_128a63ef33bc4cf891d684fad58e7f2d?ver=11.6.1'])

We are constructing the wrong name for the icontrol_fqdn and failing to find expected objects, in this case the self-ip

**Comment by ssorenso** [comment]
MD5Sum: 1bd6249c8360c9cdb8257e51a2311cc1

**Comment by ssorenso** [comment]
More related entries:
* `openstack_agent_mitaka_12.1.2-overcloud.7.consoleText`
  * Type: failures
  * Test: `test_featureoff_nosegid_common_lb_net`
  * Sum: `md5sum:794560402814db28122e3e5470242e4f`

**Comment by ssorenso** [comment]
I no longer see these failures in test within nightly, and the majority of the tests that ran into this are now either passing or running into new issues that are within their tests.

Closing this issue for now.
