### ISSUE TITLE
Build Package automation

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#592]
* Title: Build package automation
* Attachments: None
* Details: This is an enhancement

#### OpenStack Release
WIP

#### Description
In order to handle the:

* Detection of issues with Linux package building
* Detect discrepancies in dependencies.
  * The automation around generalizing build requirements and make the package building process more future proof 

#### Agent Version
Not set

#### Operating System
Both Ubuntu 14.04 (trusty) and CentOS 7

#### OpenStack Release
Not set

#### Description
This is not to handle a bug; however, it does expand up what the bug #494 fixed.

#### Deployment
This is not relevant.

**Comment by richbrowne** [comment]
Done.
