### ISSUE TITLE
RHEL 7.3 OSPv9 install does not have all needed python packages after agent RPM install

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#593]
#### Agent Version
9.0.2-1 RPM install

#### Operating System
RHEL 7.3

#### OpenStack Release
Mitaka

#### Description
After properly installing the agent via RPMs (not pip as described in the docs) so as to not pollute the controller with non-supported python packages, the agent service does not start as it is missing python-ordereddict RPM which is not available in the OSPv9 repositories. It's not marked as a dependency for the f5-openstack-agent RPM package.

We RPM installed

f5-icontrol-rest
f5-sdk
f5-openstack-agent

from the downloaded RPM packages for release 9.0.2-1 and it's dependent versions.

It is important to note that python-pip is not available as an RPM install in the OSPv9 repositories, thus you must install PIP from source. This too breaks the supported packages on the RHEL host. 

Here is what I did to fix the issue and get the agent running via its systemd unit file.

This breaks the host as it directly installs python packages in the system PYTHONPATH.

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
pip install ordereddict

#### Deployment
Standard Controller node from OSPv9

#### Prority
priority 5

We just need to figure out how to properly upstream or remove dependencies which are not part of the OSPv9 repos.

**Comment by richbrowne** [comment]
This is an SDK dependency issue.  I had them remove the dependency on ordered-dict by finding a suitable replacement.

**Comment by mattgreene** [comment]
This is fixed via f5-sdk 2.2.2 RPMs and will show up in the next agent release.

**Comment by jgruber** [comment]
upgraded to P1 as this is now a blocker for Private Cloud bundle release with OSPv9

**Comment by dflanigan** [comment]
Duplicated in https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/475

**Comment by dflanigan** [comment]
Duplicate F5Networks/f5-openstack-lbaasv2-driver#475 is closed.
