### ISSUE TITLE
Singlebigip test setup error for BigIP 11.6.1 and 12.1.1

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-agent#654]
* Details: This issue occurs while running "singlebigip" tests against BigIP 11.6.1 and 12.1.1

#### OpenStack Release
Liberty

#### Description
This issue can be reproduces by running f5-openstack-agent singlebigip tests using buildbot-sandbox. The trtl results also show the same error:
http://trtl.pdbld.f5net.com/results/projects/singlebigip_f5-openstack-agent_liberty-11_6_1-overcloud/sessions/v8.3.0.b2-8-gb4b1a0f_20170405-004804@20170405-004804/suites/systest.projects.singlebigip_f5-openstack-agent_liberty-11_6_1-overcloud.test_stats.teststats/tests/test_get_tenant_count/

#### Agent Version
v8.3.0

#### OpenStack Release
Liberty

#### Deployment
In the buildbot sandbox, force a build against liberty branch and agent repo. In the waterfall view of the build you can look at the log file and this failure listed under BigIP 11.6.1 and 12.1.1 singlebigip tests.

**Comment by zancas** [comment]
Because of the release I will be working against 8.3.1.b1.

**Comment by zancas** [comment]
By inspection of:

http://trtl.pdbld.f5net.com/results/projects/singlebigip_f5-openstack-agent_liberty-12_1_1-overcloud/sessions/

and


http://trtl.pdbld.f5net.com/results/projects/singlebigip_f5-openstack-agent_liberty-11_6_1-overcloud/sessions/

I conclude that this issue has been resolved.
