### ISSUE TITLE
Member updates failing due to missing address

### ISSUE THREAD

**Issue by abattye** [F5Networks/f5-openstack-agent#680]
Hi, 

We are seeing the following error when trying to update pools https://gist.github.com/abattye/29dffbadf1fbcdd88b293847f2a66393. It maybe related to https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/544 because we are seeing this on pools which have corrupted nova managed port, however its may be unrelated. It appears the exception is not caught and the update to all pools related to the LB are rolled back. 

We have patched to just guard against the missing address, but it would be interesting to know why the member address is missing. This is the dict, which I think is returned from the API call to the device, {'session': 'user-enabled', 'ratio': 1, 'name': u'10.180.0.35%5:443', 'partition': u'Project_b7c88763cfb944349b6ac8b0c9850f15'}

We are working with the 9.3.0 codeline.

Thanks

Andrew

**Comment by jlongstaf** [comment]
We have seen this issue for other customers when IP addresses are exhausted. We will apply a fix to guard against the KeyError.
