### ISSUE TITLE
f5-oslbaasv2-agent is not found

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#683]
When installing the agent on an Ubuntu system, I cannot start the agent because the f5-oslbaasv2-agent script is not executable.

Workaround:
I need to chmod +x /etc/init.d/f5-oslbaasv2-agent

**Comment by mattgreene** [comment]
@richbrowne Please rewrite using the proper issue template.

**Comment by dflanigan** [comment]
duplicate of #735

**Comment by mattgreene** [comment]
Issue #735 is closed.
