### ISSUE TITLE
Creating or changing pool member admin state does not change pool member enabled state

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#707]
Title: Creating a member with admin_state_up False should create a pool member which is disabled and changing a member admin_state_up should alter the enable / disable status of the pool member.

#### OpenStack Release

9.3

#### Agent Version

9.3.0

#### Operating System

Centos7

#### OpenStack Release

Mitaka

#### Description

If you create a member with admin_state_up = False, the pool member should be disabled.

#### Deployment

From the neutron CLI issue:

Creating a member with admin_state_up False does not create a pool member with a disabled state.

Once created making an REST call to change admin_state_up attribute to False does not disable the pool member for the member.

Once created making an REST call to change admin_state_up attribute to False does not enable the pool member for the member if it was disabled.

**Comment by jgruber** [comment]
Self service of pool member enable / disable is considered a primary orchestration use case. Please raise the priority of this one.

**Comment by jgruber** [comment]
Just confirmed that:

neutron lbaas-member-update --admin-state-up=False [member] [pool]

is not changing the enabled state of the pool member either.

**Comment by mattgreene** [comment]
@jgruber P2 means we will pull it in as soon as practical to fix.  We expect to cut new official releases with this, and other priority fixes, prior to the normal end-of-cycle release.  Please send us the set of priority bugs so we can fix them all in one release.

**Comment by jgruber** [comment]
Working on that. I'm cleaning out all the issues which I can confirm are fixed moving from 9.3.0 to 9.3.1b.

**Comment by dflanigan** [comment]
From @jlongstaf : This is caused by a bug in the SDK. Opened GitHub issue and submitted a fix for SDK.
