### ISSUE TITLE
[DOC]: broken link for agent v8.2.0

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-agent#722]
Hi

In the page http://f5-openstack-agent.readthedocs.io/en/v8.2.0/ there is a link to https://github.com/F5Networks/f5-openstack-agent/releases/download/v8.2.0.b2/f5-openstack-agent-8.2.0-1.el7.noarch.rpm which is not existent.

Could you please fix the link and double check that the dependencies are the right?

Many thanks

**Comment by mattgreene** [comment]
This bug has been fixed for newer releases, starting with 8.3.0.  We do not currently regenerate documentation for previous releases, as it is generated as part of the build release process.
