### ISSUE TITLE
agent should report as down to neutron when communication is lost to any associated BIG-IP

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#730]
#### Agent Version
9.3.1b

#### Operating System
Centos 7.3

#### OpenStack Release
Mitaka

#### Description
If iControl communication can not be established with any BIG-IP (standalone or pair) for whatever reason, the agent should immediately report to neutron agent extension as 'down' such that no further scheduling of LBaaS tasks be scheduled to the agent. 

Currently making a BIG-IP unreachable does not report to neutron that it is down. Only a connection timeout on a provisioning request causes the object to reach a ERROR provisioning_state. The additional problem is that if the first BIG-IP in the stored array is the online, the provisioning process starts leaving the configuration inconsistent or leaves objects stranded on the BIG-IP and Neutron.

#### Deployment
On the either BIG-IP in a pair associated with an agent:

    `bigstart stop`

to completely stop provisioning access.

Provision lbaas objects.

**Comment by jgruber** [comment]
We need to add an ini config variable to shorten the default timeout in the BIG-IP connection.

**Comment by jgruber** [comment]
We should also 'SIGABRT' the agent process when a connection failure happens.

**Comment by jgruber** [comment]
I would propose that the answer to this is to utilize each agent's admin_state_up attribute, setting it explicitly whenever there is any kind of communications issue with the agent's BIG-IP. This also opens up the opportunity to let the provider mark an agent down when they desire to do maintenance through the neutron agent extension API themselves.

The agent should attempt to set its admin_state_up to False before it attempts to react to any failures on the BIG-IP side. That way scheduling can be re-routed immediately.. assuming we change the scheduler to pay attention to the admin_state_up attribute. 

Currently the lbaas agent_scheduler will only send a provisioning task to an alternative agent in the same  environment and environment_group if the currently bound agent for the loadbalancer (stored in the neutron.lbaas_loadbalanceragentbindings table) 'alive' attribute is False at the time of the request.

By default, with the neutron agent extension, the 'alive' attribute is not stored, but is a mixin property which is calculated based the stored value of the heartbeat_timestamp value compared to global neutron config agent_down_time (75 seconds by default). If the heartbeat_timestamp is older then agent_down_time seconds, the agent 'alive' attribute is set to False. 75 seconds is a long time for requests to queued to an agent which is having problems communicating to its assigned BIG-IPs.

The heartbeat_timestamp attribute for an agent is set in the agent service whenever an agent update is called through the RPC. You can not set this attribute explicitly in an update, it is always populated by a timestamp on the neutron server side. While there is a 'version' factor which can used to upgrade from version of an agent to the next, trying to change how the agent extension updates the heartbeat_timestamp to force an agent alive state is probably not smart hack.

The agent extension does have an admin_state_up attribute which can be explicitly set in the update_agent RPC call. Currently the default TenantScheduler.get_lbaas_agent_hosting_loadbalancer does not consider this attribute when decided which agent to send a request, but it could. Changing this method to support the admin_state_up attribute as well as the 'alive' attribute would allow for explicit signally from the f5-openstack-agent that it has a problem which must result in scheduled provisioning tasks being sent to an alternative agent. 

The other consideration is if a bound loadbalancer should be 'rebound' to an alternative agent when the currently bound agent is found to be down (by either the 'alive' or the admin_state_up) attribute. I would suggest that if an agent is not 'alive' (down for over 75 seconds), a rebinding to a currently 'alive' agent in the group should be attempted. The rebinding is trivial as the db model is already called in our TenantScheduler. 

binding = agent_scheduler.LoadbalancerAgentBinding()
binding.agent = chosen_agent
binding.loadbalancer_id = loadbalancer.id
context.session.add(binding)

If all agents are having problem with BIG-IPs for which they are assigned, then all agents should set their admin_state_up to False, and the scheduler will not be able to find a valid agent to fulfill the request. While this is drastic to down the entire control plane when there may be a valid BIG-IP to provision (only one of the sync-failover group members are down), it prevents us from having to handle device syncing after a failure at this phase. 

Note that if the provider uses the neutron agent extension API to mark an agent admin_state_up to True when the sync-failover group is not at full strength, we can still get requests sent to an agent which should not fulfill them, but that is no worse then the request queuing up for the 75 second timer today.

**Comment by richbrowne** [comment]
Fixed by issue 1085
