### ISSUE TITLE
Add notice to docs about move to clouddocs

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-agent#741]
#### Agent Version
N/A

#### Operating System
N/A

#### OpenStack Release
Liberty

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
I need to add a notice to the documentation regarding the move to clouddocs. It will look like this:
![2017-05-25_11-47-43](https://cloud.githubusercontent.com/assets/12143793/26462941/fe3c6f6e-413f-11e7-9efe-0ca50a6aac8a.png)

**Comment by dflanigan** [comment]
Commit is in master. Looks like merge into liberty did not reference this issue to close it automatically.
