### ISSUE TITLE
Fix permissions issue where Jenkinsfile downloads systest results files.

### ISSUE THREAD

**Issue by larkinkevin** [F5Networks/f5-openstack-agent#752]
* Title: Fix permissions issue where Jenkinsfile downloads systest results files.

#### Description
- Nightly regression jobs report errors like "cp: preserving times for 'x': Operation not permitted" at the point where they try to download systest results logs.
- While not a blocker (because the job *does* run to completion and *does* successfully download the results files), this unexpected error is a nuisance because it causes the Jenkins weather report to remain stormy.

**Comment by dflanigan** [comment]
Fixed with a Patch from  Za.
