### ISSUE TITLE
Create Universal Source of Truth for Dependencies

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#765]
* Title: Create Universal Source of Truth for Dependencies
* Attachments: None
* Details:
  * Create a means by which to reference in just one place where all dependencies are to execute `pip install ./` for the `f5-openstack-agent` lies
  * This does not effect or impact documentation sources that will still need to be edited manually for each release

#### OpenStack Release
TBD - First to be checked into Liberty

#### Description
This enhancement should be like the [f5-sdk's RPM and DEB package generation scripts](https://github.com/F5Networks/f5-common-python/issues/980); however, the current scope is to only create the one file as a universal truth.

**Comment by zancas** [comment]
ALSO...   the agent must respect:

https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=

In the same way that the driver does.

**Comment by ssorenso** [comment]
@zancas, correct. This should make it so that the agent will behave like the driver when creating RPM and DEB packages.

At the moment, I've got a few other priorities, so this has hit the back burner for now...

**Comment by ssorenso** [comment]
So I drastically limited what this change does.  It is simply focused on providing a single file as a universal truth for dependencies.

The RPM/DEB intelligence enhancement will not come into play until we have a more clear idea on how to approach this.  I have a few ideas, but this may be put elsewhere besides having a copy in each repo.  This is addressed in the pull request #812 added above.
