### ISSUE TITLE
Self IP not created for pool members on separate subnets, same VLAN

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#778]
#### Agent Version
8.3.0

#### Operating System
CentOS

#### OpenStack Release
Liberty

#### Description
For this load balancing configuration:
- one pool
- two pool members
- each member on the same VLAN network
- each member on different subnets

A single self IP is created for the first subnet, but another self IP is not created for the second subnet. Essentially, the agent implicitly assumes that pool members either are on the same subnet, or if they are on different subnets, the subnets are on different networks. The use case of pool members allocated on different subnets but the same network is not working.

#### Deployment
Multiple controllers and agents, BIG-IP LTM 11.6.1 HF2 configured in HA pair.

**Comment by zhangxuanyuan** [comment]
I have modified _get_subnets_to_assure function in f5-openstack-agent/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py, I changed networks[network['id']] to networks[subnet['id']], and it worked, but I can't confirm whether this modification will affect other functions.
Looking forward to your solution. Thank you!

**Comment by jlongstaf** [comment]
Yes, that's the solution we have as well. We don't think it will affect other functions, but we are doing full regression testing today. Thank you.
