### ISSUE TITLE
f5 objects lost when reboot f5 ltm

### ISSUE THREAD

**Issue by Sinan828** [F5Networks/f5-openstack-agent#806]
* Title: f5 objects lost when reboot f5 ltm

#### OpenStack Release
mitaka
#### Agent Version
9.3.1

#### Operating System
centos7

#### Description
f5 objects lost when reboot f5 ltm.
please see the attached.
[vlb_objects_lost.docx](https://github.com/F5Networks/f5-openstack-agent/files/1158438/vlb_objects_lost.docx)

**Comment by Sinan828** [comment]
logs:
[logs.tar.gz](https://github.com/F5Networks/f5-openstack-agent/files/1158451/logs.tar.gz)
qkview:
[sdn.mylab.cn.qkview.zip](https://github.com/F5Networks/f5-openstack-agent/files/1158459/sdn.mylab.cn.qkview.zip)

**Comment by Sinan828** [comment]
I didn't see save operation code in agent.

**Comment by Sinan828** [comment]
@pjbreaux I can't open the issue link you give it.

**Comment by pjbreaux** [comment]
@Sinan828: try it now. Thanks.

**Comment by Sinan828** [comment]
@pjbreaux You can see the word doc, when reboot f5 device, vip/pool/member all of them lost and not recreate.

**Comment by richbrowne** [comment]
Backup running config is added to the agent refactor in next release.
