### ISSUE TITLE
TestStats.test_get_cpu_health_score Failure due to AttributeError test_stats.py

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#846]
* Title: TestStats.test_get_cpu_health_score Failure due to AttributeError test_stats.py
* Attachments:
* Details: 

##### Tests impacted:
* `openstack_agent_mitaka_12.1.1-overcloud.87.consoleText.TestStats.test_get_cpu_health_score`

##### Traceback:
```
    def test_get_cpu_health_score(self, mgmt_root, stats_helper):
>       score = stats_helper.get_cpu_health_score(mgmt_root)
E       AttributeError: 'StatHelper' object has no attribute 'get_cpu_health_score'

test_stats.py:66: AttributeError
```

##### Attributed sums:
md5sum:57cceb1b75aa96c04bad351117736ba0
reduced(md5sum):d41d8cd98f00b204e9800998ecf8427e

#### OpenStack Release
* Mitaka

#### Agent Version
* Mitaka - `1b032716919cd36ee8bb849887b587acc63e725a`

#### Operating System
Nightly

#### Deployment
* Overcloud

**Comment by ssorenso** [comment]
Other hits for similar code:
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_composite_score`
  * Sum: `md5sum:56939d87eb3db790e0e0f96e5f0d212c`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_composite_score`
  * Sum: `md5sum:5f0e03b8f70cb6d3a4c9b13d3c5d9e0c`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_composite_score`
  * Sum: `md5sum:eb978be57e37849249f1ae38c0f7ac88`
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_cpu_health_score`
  * Sum: `md5sum:8d7f0eb1c261f90daddb63b8c4cbbccd`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_cpu_health_score`
  * Sum: `md5sum:b8fb1c26b97ad4220851c39f979209c6`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_cpu_health_score`
  * Sum: `md5sum:e7e67aea852926564b9a434921368bc3`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_inbound_throughput`
  * Sum: `md5sum:9b81c120c308ea7a88542e43d9161067`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_inbound_throughput`
  * Sum: `md5sum:e63b94edd729ca03e725bcf62aa1c67c`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_mem_health_score`
  * Sum: `md5sum:2539886f4c157d008fc3a7d514aee5a0`
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_mem_health_score`
  * Sum: `md5sum:3a3a4ed482af777750cafae014ccbb65`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_mem_health_score`
  * Sum: `md5sum:8a67eead388892751275ce6857f6e68a`
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_node_count`
  * Sum: `md5sum:34f90715f4e659cd1ec9386c9135aa65`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_node_count`
  * Sum: `md5sum:8a5a78f103e14d983dade0798cffd719`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_node_count`
  * Sum: `md5sum:d7ef695a992046c1c5d0f8a6c7aa55cf`
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_route_domain_count`
  * Sum: `md5sum:8bc96b59d0f198b337ab651df2089cc1`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_route_domain_count`
  * Sum: `md5sum:bed29328a5f79077737786af14b2657d`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_route_domain_count`
  * Sum: `md5sum:ce050436f455db8b174ea8112c8ab5e4`
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_tenant_count`
  * Sum: `md5sum:3bc122a5188ef45600464d0c3280d35c`
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_tenant_count`
  * Sum: `md5sum:536ca622e7ff3c4c6a000a5f46fc274b`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `TestStats.test_get_tenant_count`
  * Sum: `md5sum:543a7b74a7fd9f49ff7cc9a588f6f744`

**Comment by richbrowne** [comment]
Janaki can you verify this as fixed?

**Comment by richbrowne** [comment]
THis is no longer in the tests.  The implementation has changed.
