### ISSUE TITLE
Test failed to cleanup singlebigip/test_network.py:test_arp_delete_by_network

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#863]
* Title: Test failed to cleanup singlebigip/test_network.py:test_arp_delete_by_network
* Attachments: 
* Details: 

##### Traceback:
```
    def teardown():
>       system_helper.delete_folder(mgmt_root, default_partition)

test_network.py:72:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5_openstack_agent/lbaasv2/drivers/bigip/system_helper.py:41: in delete_folder
    obj.delete()
../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5/bigip/resource.py:1058: in delete
    self._delete(**kwargs)
../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5/bigip/resource.py:1040: in _delete
    response = session.delete(delete_uri, **requests_params)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <icontrol.session.iControlRESTSession object at 0x7f518a5545d0>
RIC_base_uri = 'https://10.190.25.59:443/mgmt/tm/sys/folder/~test/', kwargs = {}
partition = '', sub_path = '', suffix = '', identifier = ''
uri_as_parts = False, transform_name = False
REST_uri = 'https://10.190.25.59:443/mgmt/tm/sys/folder/~test/'

    @functools.wraps(method)
    def wrapper(self, RIC_base_uri, **kwargs):
        partition = kwargs.pop('partition', '')
        sub_path = kwargs.pop('subPath', '')
        suffix = kwargs.pop('suffix', '')
        identifier, kwargs = _unique_resource_identifier_from_kwargs(**kwargs)
        uri_as_parts = kwargs.pop('uri_as_parts', False)
        transform_name = kwargs.pop('transform_name', False)
        if uri_as_parts:
            REST_uri = generate_bigip_uri(RIC_base_uri, partition, identifier,
                                          sub_path, suffix,
                                          transform_name=transform_name,
                                          **kwargs)
        else:
            REST_uri = RIC_base_uri
        pre_message = "%s WITH uri: %s AND suffix: %s AND kwargs: %s" %\
            (method.__name__, REST_uri, suffix, kwargs)
        logging.debug(pre_message)
        response = method(self, REST_uri, **kwargs)
        post_message =\
            "RESPONSE::STATUS: %s Content-Type: %s Content-Encoding:"\
            " %s\nText: %r" % (response.status_code,
                               response.headers.get('Content-Type', None),
                               response.headers.get('Content-Encoding', None),
                               response.text)
        logging.debug(post_message)
        if response.status_code not in range(200, 207):
            error_message = '%s Unexpected Error: %s for uri: %s\nText: %r' %\
                            (response.status_code,
                             response.reason,
                             response.url,
                             response.text)
>           raise iControlUnexpectedHTTPError(error_message, response=response)
E           iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.190.25.59:443/mgmt/tm/sys/folder/~test/
E           Text: u'{"code":400,"message":"0107082a:3: All objects must be removed from a partition (test) before the partition may be removed, type ID (6090)","errorStack":[],"apiError":3}'

/usr/local/lib/python2.7/dist-packages/icontrol/session.py:272: iControlUnexpectedHTTPError
```
##### Tests:
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_arp_delete_by_network`
  * Sum: `0ab3974d6817174d1b73cce9e0826517`

#### OpenStack Release
Mitaka

#### Agent Version
mitaka - 323189b9db8e3298832a1c7b3623ce33adc1a632

#### Operating System
Nightly

#### Deployment
singlebigip agent functional tests

**Comment by ssorenso** [comment]
Relatively related bugs:

`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_get_vxlan_tunnel_key`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_get_vlan_id`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_get_selfip_addr`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_get_selfips`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_delete_selfip`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `TestRouteDomain.test_route_domain_CRUD`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `TestRouteDomain.test_route_domain_get_ids`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `TestRouteDomain.test_route_domain_get_names`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `TestRouteDomain.test_route_domain_get_vlans_by_id`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`
`openstack_agent_mitaka_12.1.1-overcloud.90.consoleText`
  * Type: errors
  * Test: `test_arp_delete_by_network`
  * md5sum: `0ae62d8f841c6d62aa46e631143abef3`

**Comment by richbrowne** [comment]
I believe that this is a known test failure.  Even when they were originally written.  There is a know issue with management of ARP info with REST API
