### ISSUE TITLE
test_get_mgmt_addr_by_device assert failure in expected test state

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#875]
* Title: test_get_mgmt_addr_by_device assert failure in expected test state
* Attachments: 
* Details: 

##### Suggested Error Type:
Bug - the justification is that the test fails in the test itself due to an unexpected result from a pre-set state.  The state appears to be reached, but the test expects a specific state back from the agent that is not reached.  In not so many words, the test appears to be doing what it should be, but the behavior of the agent has changed.

##### Traceback
From Mitaka:
```
symbols = <pytest_symbols.models.Symbols object at 0x7f359263f190>
mgmt_root = <f5.bigip.ManagementRoot object at 0x7f3591724d90>

    def test_get_mgmt_addr_by_device(symbols, mgmt_root):
        pp(dir(symbols))
        device_name = mgmt_root._meta_data['device_name']
        devices = cm.devices(mgmt_root)
        addr = cm.get_mgmt_addr_by_device(mgmt_root, device_name)
        mgmt_ips = (symbols.bigip_mgmt_ip, symbols.bigip_mgmt_ip_public)
>       assert addr in mgmt_ips
E       AssertionError: assert None in ('172.16.2.224', '10.190.24.89')

test_cluster.py:81: AssertionError
```
From Newton:
```
symbols = <pytest_symbols.models.Symbols object at 0x7fe3d50e8c10>
mgmt_root = <f5.bigip.ManagementRoot object at 0x7fe3d41cbe10>

    def test_get_mgmt_addr_by_device(symbols, mgmt_root):
        pp(dir(symbols))
        device_name = mgmt_root._meta_data['device_name']
        devices = cm.devices(mgmt_root)
        addr = cm.get_mgmt_addr_by_device(mgmt_root, device_name)
        mgmt_ips = (symbols.bigip_mgmt_ip, symbols.bigip_mgmt_ip_public)
>       assert addr in mgmt_ips
E       AssertionError: assert None in ('172.16.2.225', '10.190.25.10')

test_cluster.py:81: AssertionError
```
From Liberty:
```
symbols = <pytest_symbols.models.Symbols object at 0x7f46a5943dd0>
mgmt_root = <f5.bigip.ManagementRoot object at 0x7f46a4a6f650>

    def test_get_mgmt_addr_by_device(symbols, mgmt_root):
        pp(dir(symbols))
        device_name = mgmt_root._meta_data['device_name']
        devices = cm.devices(mgmt_root)
        addr = cm.get_mgmt_addr_by_device(mgmt_root, device_name)
        mgmt_ips = (symbols.bigip_mgmt_ip, symbols.bigip_mgmt_ip_public)
>       assert addr in mgmt_ips
E       AssertionError: assert None in ('172.16.2.223', '10.190.24.88')

test_cluster.py:81: AssertionError
```
All of these fail with about the same reason in the same segment of code.

##### Impacted tests:
* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `test_get_mgmt_addr_by_device`
  * Sum: `md5sum:37d498f07e7829b7c577b04308c8ae2a`
* `openstack_agent_newton_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `test_get_mgmt_addr_by_device`
  * Sum: `md5sum:47c8b50c3cb4ae1ffa3d3eb8c41709d5`
* `openstack_agent_liberty_12.1.2-overcloud.6.consoleText`
  * Type: failures
  * Test: `test_get_mgmt_addr_by_device`
  * Sum: `md5sum:c7962d1f842a388b7cbd076d2fcdfabe`

#### OpenStack Release
All supported

#### Agent Version
* Liberty - bc50989f5c75da211189c03351aca7cd03e67ccf
* Mitaka - b096048814d641ff27ddc0be0babf70a6a6d230d
* Newton - 2060bb6215e25a86e5dfdfebf42e1f6c5ad5d464

#### Operating System
nightly

**Comment by richbrowne** [comment]
Passing
