### ISSUE TITLE
test_get_gre_tunnel_key failing in teardown due to missing 'uri' key

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#897]
* Title: test_get_gre_tunnel_key failing in teardown due to missing 'uri' key
* Attachments: For bugs, attach the agent log and configuration files
  * /etc/neutron//services/f5/f5-openstack-agent.ini
  * /var/log/neutron/f5-openstack-agent.log
* Details: 

##### Suggested Issue Type
Test Error

##### Traceback
```
_________________ ERROR at teardown of test_get_gre_tunnel_key _________________

    def teardown():
>       delete_resource(resource)

test_network.py:60:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_network.py:52: in delete_resource
    resource.delete()
../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5/bigip/resource.py:1058: in delete
    self._delete(**kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <f5.bigip.tm.net.tunnels.Tunnel object at 0x7f22c55f9690>, kwargs = {}
requests_params = {}

    def _delete(self, **kwargs):
        """wrapped with delete, override that in a subclass to customize """
        requests_params = self._handle_requests_params(kwargs)

>       delete_uri = self._meta_data['uri']
E       KeyError: 'uri'

../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5/bigip/resource.py:1032: KeyError
```

##### Impacted Tests:

* `openstack_agent_liberty_12.1.2-overcloud.15.consoleText`
  * Type: failures
  * Test: `test_get_gre_tunnel_key`
  * `md5sum:08bfebe97f5f5e506eb4cd295f3198ba`
* `openstack_agent_mitaka_12.1.2-overcloud.15.consoleText`
  * Type: failures
  * Test: `test_get_gre_tunnel_key`
  * `md5sum:08bfebe97f5f5e506eb4cd295f3198ba`
* `openstack_agent_newton_12.1.2-overcloud.15.consoleText`
  * Type: failures
  * Test: `test_get_gre_tunnel_key`
  * `md5sum:08bfebe97f5f5e506eb4cd295f3198ba`

#### OpenStack Release
All f5-supported

#### Agent Version
* Mitaka - 87943414cebfd5461f33826d7a2c71ff192a947b
* Liberty - bc50989f5c75da211189c03351aca7cd03e67ccf
* Newton - ec1a5809fe1e370c070ec625e1833ed2f59022a2

#### Operating System
Nightly Agent tests

**Comment by ssorenso** [comment]
Also impacts `test_get_gre_tunnel_key`:
* `openstack_agent_liberty_12.1.2-overcloud.15.consoleText`
  * Type: errors
  * Test: `test_get_gre_tunnel_key`
  * `md5sum:5deff57ef87050fb1fc0dcdeb1680b4e`
* `openstack_agent_mitaka_12.1.2-overcloud.15.consoleText`
  * Type: errors
  * Test: `test_get_gre_tunnel_key`
  * `md5sum:5deff57ef87050fb1fc0dcdeb1680b4e`
* `openstack_agent_newton_12.1.2-overcloud.15.consoleText`
  * Type: errors
  * Test: `test_get_gre_tunnel_key`
  * `md5sum:5deff57ef87050fb1fc0dcdeb1680b4e`
```
_________________ ERROR at teardown of test_get_gre_tunnel_key _________________

    def teardown():
>       delete_resource(resource)

test_network.py:60:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_network.py:52: in delete_resource
    resource.delete()
../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5/bigip/resource.py:1058: in delete
    self._delete(**kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <f5.bigip.tm.net.tunnels.Tunnel object at 0x7f22c55f9690>, kwargs = {}
requests_params = {}

    def _delete(self, **kwargs):
        """wrapped with delete, override that in a subclass to customize """
        requests_params = self._handle_requests_params(kwargs)

>       delete_uri = self._meta_data['uri']
E       KeyError: 'uri'

../../../.tox/singlebigip/local/lib/python2.7/site-packages/f5/bigip/resource.py:1032: KeyError
```

**Comment by richbrowne** [comment]
These tests are passing.
