### ISSUE TITLE
test_device_name: AssertionError: `assert cm.get_device_name(mgmt_root) == device_name`

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-agent#982]
* Title: test_device_name: AssertionError: `assert cm.get_device_name(mgmt_root) == device_name`
* Attachments: 
* Details: 

##### Suggested Issue Type
Bug.  At least until ruled out as this is in test code and indicates a change in behavior

##### Traceback
```
mgmt_root = <f5.bigip.ManagementRoot object at 0x7fbc98652cd0>

    def test_device_name(mgmt_root):
        device_name = mgmt_root._meta_data['device_name']
>       assert cm.get_device_name(mgmt_root) == device_name
E       assert 'bigip1' == None
E        +  where 'bigip1' = <bound method ClusterManager.get_device_name of <f5_openstack_agent.lbaasv2.drivers.bigip.cluster_manager.ClusterManager object at 0x7fbc9b74b190>>(<f5.bigip.ManagementRoot object at 0x7fbc98652cd0>)
E        +    where <bound method ClusterManager.get_device_name of <f5_openstack_agent.lbaasv2.drivers.bigip.cluster_manager.ClusterManager object at 0x7fbc9b74b190>> = <f5_openstack_agent.lbaasv2.drivers.bigip.cluster_manager.ClusterManager object at 0x7fbc9b74b190>.get_device_name

test/functional/singlebigip/test_cluster.py:34: AssertionError
```

##### Impact:
* `openstack_agent_mitaka_12.1.2-overcloud.63.consoleText`
  * failures
  * `test_device_name`
  * `md5sum:276adeab51aad0abcee972dacdd10940`

#### OpenStack Release
Mitaka

#### Agent Version
mitaka - `98581dd`

#### Operating System
nigthly

**Comment by dflanigan** [comment]
@ssorenso @zancas @pjbreaux Is this bug the result of the nightly setup issue where BigIP is not ready when the tests start running ? (Now that the tests start running faster when the containerized agent test runner is used.)

**Comment by ssorenso** [comment]
@dflanigan, that may be; however, if the BIG-IP were not ready, then we would see a whole lot more errors.  This seems to reoccur quite often.  There's been 6 instances in the last 2 days.

**Comment by richbrowne** [comment]
Test is passing.
